"###############################################################################
" wal.vim - Use colorscheme generated by the wal plugin
"           https://github.com/dylanaraps/wal.vim
"###############################################################################
colorscheme wal
