# Executed from an interactive shell, once per login.

# Inherit .profile
if [ -f ~/.profile ]; then . ~/.profile; fi
# Get the environment variables
if [ -f ~/.bashrc ]; then . ~/.bashrc; fi
# Get machine-specific aliases
if [ -f ~/.bash_profile.local ]; then . ~/.bash_profile.local; fi
# Enable bash completion if installed
if [ -f /usr/local/etc/bash_completion.d ]; then . /usr/local/etc/bash_completion.d
elif type -P brew &> /dev/null; then . `brew --prefix`/etc/bash_completion
fi
# Path suffixes to ignore when doing shell completion
export FIGNORE=VS:svn
export PATH=/chub/bin:~/bin:$GRAILS_HOME/bin:/usr/local/bin:$PATH

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/ldhanson2/.sdkman"
[[ -s "/Users/ldhanson2/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/ldhanson2/.sdkman/bin/sdkman-init.sh"
