# Executed from an interactive shell, once per login.
# See .bashrc for non-interactive

# Inherit .profile
if [ -f ~/.profile ]; then . ~/.profile; fi
# Get the environment variables
if [ -f ~/.bashrc ]; then . ~/.bashrc; fi
# Get machine-specific aliases
if [ -f ~/.bash_profile.local ]; then . ~/.bash_profile.local; fi
# Enable bash completion if installed
if [ -f /usr/local/etc/bash_completion.d ]; then . /usr/local/etc/bash_completion.d
elif type -P brew &> /dev/null; then . `brew --prefix`/etc/bash_completion
fi
# Path suffixes to ignore when doing shell completion
export FIGNORE=VS:svn
export PATH=~/bin:$GRAILS_HOME/bin:/usr/local/bin:$PATH

SSH_ENV="$HOME/.ssh/environment"

function start_agent {
     echo "Initialising new SSH agent..."
     /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
     echo succeeded
     chmod 600 "${SSH_ENV}"
     . "${SSH_ENV}" > /dev/null
     /usr/bin/ssh-add;
}

# Source SSH settings, if applicable
if [ -f "${SSH_ENV}" ]; then
     . "${SSH_ENV}" > /dev/null
     #ps ${SSH_AGENT_PID} doesn't work under cywgin
     ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
         start_agent;
     }
else
     start_agent;
fi

# Enable git completion if installed
if [ -f ~/.git-completion ]; then 
    . ~/.git-completion;
    # Show current branch in prompt
    GIT_PS1='$(__git_ps1 " (%s)")'
    #if ! [ -z "$GIT_PS1" ]; then GIT_PS1=" $GIT_PS1 "; fi
    export GIT_PS1_SHOWDIRTYSTATE=true
    export GIT_PS1_SHOWSTASHSTATE=true
    export GIT_PS1_SHOWUNTRACKEDFILES=true
fi

# Set up Docker environment
eval $(docker-machine env default)
export DOCKER_PS1='$(__docker_machine_ps1 " [%s]")'

# Prompt silliness
GREEN="\[\e[00;32m\]"
BLUE="\[\e[01;34m\]"
BLACK="\[\e[00;30m\]"
WHITE="\[\e[01;37m\]"
RED="\[\e[00;31m\]"
export PS1="$GREEN\u@\h $WHITE\W$RED$GIT_PS1$DOCKER_PS1 $BLUE\[\e[00m\]➔  "

# Store more history, ignoring dupes
export HISTCONTROL=erasedups
export HISTSIZE=1000
shopt -s histappend

# Vim, everywhere.
export EDITOR=vim

# vi-style command editing
set -o vi
# enable extended globbing
shopt -s  extglob

export EDITOR=vim

# Set aliases for interactive terminal use
alias vi=vim
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'
alias l='ls -lAh'
alias la='ls -a'
alias ll='ls -l'
alias t='tail -f ~/log'
alias g=git
alias dme='eval "$(docker-machine env)"'
# Work around non-awesome Solaris 'ls' which lacks color
if [[ `uname` =~ "SunOS" ]]; then
    alias ls='ls -F'
elif [[ `uname` =~ "Linux" ]]; then
    alias ls='ls --color=auto' 
else
    alias ls='ls -G' 
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/ldhanson2/.sdkman"
[[ -s "/Users/ldhanson2/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/ldhanson2/.sdkman/bin/sdkman-init.sh"
